name: Generate PDFs

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git repository
        uses: actions/checkout@v2

      - name: Compile Problems
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            2122_t1/problems.tex
            2122_t2/problems.tex
            2122_t3/problems.tex
            2223_t1/problems.tex
          work_in_root_file_dir: true
      
      - name: Move files
        run: |
          mv 2122_t1/problems.pdf 2122_t1.pdf
          mv 2122_t2/problems.pdf 2122_t2.pdf
          mv 2122_t3/problems.pdf 2122_t3.pdf
          mv 2223_t1/problems.pdf 2223_t1.pdf

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2 
        with:
          name: UWCS Programming Problem Sets
          path: |
            2122_t1.pdf
            2122_t2.pdf
            2122_t3.pdf
            2223_t1.pdf
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            2122_t1.pdf
            2122_t2.pdf
            2122_t3.pdf
            2223_t1.pdf